OPNAMES:
  ccinstall: "cc install"
  ccapprove: "cc approve"
  cccommit: "cc commit"
  ccinstantiate: "cc initialize"
  ccinvoke: "cc invoke"
  ccquery: "cc query"
  channelcreate: "channel create"
  channeljoin: "channel join"
  blockquery: "block query"
  channelquery: "channel query"
  profilegen: "profile generation"
  channelsign: "channel signoff"
  channelupdate: "channel update"
  anchorupdate: "anchor update"
  dashup: "dashboard up"
  dashdown: "dashboard down"
  nodeimport: "node import"
  discover: "discover"